theData <- read.table("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
theData <- theData[theData$Date %in% c("1/2/2007","2/2/2007"),]
globalActivePower <- as.numeric(theData$Global_active_power)
dateTime <- parse_date_time(paste(theData$Date, theData$Time, sep=" "), "dmy HMS") 
subMetering1 <- as.numeric(theData$Sub_metering_1)
subMetering2 <- as.numeric(theData$Sub_metering_2)
subMetering3 <- as.numeric(theData$Sub_metering_3)
globalReactivePower <- as.numeric(theData$Global_reactive_power)
voltage <- as.numeric(theData$Voltage)
png("plot4.png", width=480, height=480)
par(mfrow = c(2,2)) 
plot(dateTime, globalActivePower, type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(dateTime, voltage, type="l", xlab="datetime", ylab="Voltage")
plot(dateTime, subMetering1, type="l", ylab="Energy sub metering", xlab="")
lines(dateTime, subMetering2, type="l", col="red")
lines(dateTime, subMetering3, type="l", col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty=, lwd=2.5, col=c("black","red","blue"), bty="o")
plot(dateTime, globalReactivePower, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()